``` mermaid

sequeneceDiagram
 participate browser
 participate server

 browser-->server: POST https://studies.cs.helsinki.fi/exampleapp/notes 
 activate server
 Note left of server: Do a URL Redirect to https://studies.cs.helsinki.fi/exampleapp/notes 
 server--> browser: HTTP status code 302
 deactivate server

 Note right of browser : The browser reloads the Notes page

 browser-->server: GET https://studies.cs.helsinki.fi/exampleapp/notes 
 activate server 
 server--> browser: HTML DOCUMENT
 deactivate server

 browser-->server: GET https://studies.cs.helsinki.fi/exampleapp/main.css 
 activate server 
 server--> browser: CSS FILE
 deactivate server

 browser-->server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
 activate server 
 server--> browser: JAVASCRIPT FILE
 deactivate server

Note right of browser: The browser starts executing the Javascripts code that fetches the JSON from the server

 browser-->server: GET https://studies.cs.helsinki.fi/exampleapp/notes 
 activate server
 server--> browser: [{"content":"HTML IS GOOD","date":"06-09-2023"},...]
 deactivate server

Note right of browser :The browser executes the callback function that renders the notes

